### ISSUE TITLE
[BUG] - (Google Doc links in the pdf require access )

### ISSUE THREAD

**Issue by mouseman22** [theshmunguss1/RamHub#9]
**To Reproduce**
1. Go to the pdf
2. Right click on the google doc links --> open in new tab
3. Access required

**Screenshots**
![image](https://github.com/theshmunguss1/RamHub/assets/158526837/df8e00e6-03f0-438e-afbf-0d14936cc7ad)

**Comment by DJshelfmushroom** [comment]
Please provide examples, as well as please follow the bug report format, as it would've told you to do this.

**Comment by theshmunguss1** [comment]
This is a known issue and we are actively trying to redirect you to Github links. The reason is that the administration in the school district in which RamWorks is hosted blocked the ability to share Google Workspace files with any account outside of said district. We have no control over this problem as of now.

**Comment by theshmunguss1** [comment]
> uh huh,
>maybe don't host a huge collection of anti curriculum files in school..

It's not anti-curriculum, the links were open for a long time. It should be fixed now for all of the RamWorks Google Docs links though.
